### ISSUE TITLE
API Redesign Idea

### ISSUE THREAD

**Issue by curran** [datavis-tech/topologica#15]
The current API is starting to feel a bit cumbersome.

What if modules could define reactive functions and their inputs is a very simple way, without even importing Topologica? Then the top level program could just combine all the reactive functions into one place.

Current API example:

```js
const dataFlow = DataFlowGraph({
  fullName: λ(
    ({firstName, lastName}) => `${firstName} ${lastName}`,
    'firstName, lastName'
  )
});
```

Here's how it would look if `fullName` were split out from the data flow graph definition.

```js
const fullName = λ(
  ({firstName, lastName}) => `${firstName} ${lastName}`,
  'firstName, lastName'
);

const dataFlow = DataFlowGraph({ fullName });
```

# fn.inputs Approach

Same example with new API idea:

```js
const fullName = ({firstName, lastName}) => `${firstName} ${lastName}`;
fullName.inputs = 'firstName, lastName';

const dataFlow = DataFlowGraph({ fullName });
```

As a module:

```js
export const fullName = ({firstName, lastName}) => `${firstName} ${lastName}`;
fullName.inputs = 'firstName, lastName';
```

With hoisting:

```js
fullName.inputs = 'firstName, lastName';
export function fullName({firstName, lastName}){
  return `${firstName} ${lastName}`;
}
```

Pros:
 * `fullName` looks and feels like a normal, plain old function.
 * Use within a module feels quite natural and simple.
 * No need to import Topological and define `λ` in modules that define reactive functions.
 * With hoisting you can specify the inputs right above the function implementation, which is clear to read.

Cons
 * But then we lose the ability to define functions inline, which might be good to keep.
 * It's not clear that the structure defined is for use with Topologica (need to read the main program in addition to just the module).

# Array Approach

What if we use an array?

```js
const fullName = [
  ({firstName, lastName}) => `${firstName} ${lastName}`,
  'firstName, lastName'
];

const dataFlow = DataFlowGraph({ fullName });
```

As a module maybe it could look like this:

```js
export const fullName = [
  ({firstName, lastName}) => `${firstName} ${lastName}`,
  'firstName, lastName'
];
```

What if we want to define the function separately?

```js
const fullNameFn = ({firstName, lastName}) => `${firstName} ${lastName}`;

export const fullName = [
  fullNameFn,
  'firstName, lastName'
];
```

Pros:
 *  * No need to import Topological and define `λ` in modules that define reactive functions.

Cons
 * Who wants to define their function as the first element of an array?
 * Need to define the function separately from the reactive function, which feels unnecessary.
 * Need to remember the order of things in the array.

**Comment by curran** [comment]
@monfera Thanks a ton for these ideas! Very interesting considerations.

I really do like the idea of "no explicit declaration of inputs other than as regular function args". I'm not really happy with how currently with this library, you need to duplicate the list of dependencies (once for explicit declaration, and once to unpack them as variables).

I took the approach of having the properties more like "observables" with https://github.com/datavis-tech/reactive-function. One interesting consequence of doing this, with the topological sorting approach, was that it ended up being necessary to construct one global dependency graph, which internally ended up as one object with a bunch of properties (with auto-generated names).

It's a very interesting design space, and I'm not sure how it will all play out. The way I'm envisioning this being used is for efficiently managing DOM updates within a single visualization component. Meaning, a scatter plot would have its own instance of Topologica, and a bar chart would have its own as well. On top of that, I'm envisioning Redux being the orchestrator of it all. This is the motivation for having these properties tied to objects.

Anyway thanks a lot for weighing in! I really appreciate your thoughts here, and in perusing your links I discovered some projects I had not heard about before.

**Comment by monfera** [comment]
A tangential comment, topological sorting can be done under the hood with either approach, ie. your global namespace based implementation as well as the use of regular values (`flyd` and `crosslink` both toposort too). In the case of the latter two, there's still a graph, ie. a notion of what the transform nodes are part of, similar to your more explicit approach.
